# Generated by Django 3.2 on 2022-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='reviews.Genre', verbose_name='Жанры'),
        ),
    ]
