# Generated by Django 3.2 on 2022-12-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20221215_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitle',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre_id',
            field=models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.genre'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='titles', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанры'),
        ),
    ]
